name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: macos-latest
            compiler: gcc   # macOS runners use clang

    env:
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang' }}
      # Enable sanitizers on CI if you uncomment SANFLAGS in your Makefile:
      # ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
      # UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang curl

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install curl || true

      - name: Build app
        run: make -j

      - name: Build & run unit tests
        run: make -j test

      - name: Upload test binary and log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-artifacts
          path: |
            unit_tests
            obj/**
            webserv
